import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../../../services/auth.service';
import { User } from '../../../models/user.model';
import { ToastService } from '../../../services/toast.service';

@Component({selector:'app-admin-customers',standalone:true,imports:[CommonModule,FormsModule],template:`
<div class="page"><header><div><h1>Customers</h1><p>Create and manage storefront customer accounts.</p></div><button (click)="open()">+ Add customer</button></header>
<form *ngIf="showForm" (ngSubmit)="save()" class="card"><h2>{{editing?'Edit customer':'Add customer'}}</h2><div class="grid"><label>First name<input [(ngModel)]="form.firstName" name="firstName" required></label><label>Last name<input [(ngModel)]="form.lastName" name="lastName" required></label><label>Email<input type="email" [(ngModel)]="form.email" name="email" required></label><label>Phone<input [(ngModel)]="form.phone" name="phone"></label><label>Password {{editing?'(leave blank to keep)':''}}<input type="password" [(ngModel)]="form.password" name="password" [required]="!editing"></label><label>Status<select [(ngModel)]="form.status" name="status"><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></label></div><div class="actions"><button type="submit">Save customer</button><button type="button" class="secondary" (click)="cancel()">Cancel</button></div></form>
<div class="table"><table><thead><tr><th>Customer</th><th>Email</th><th>Phone</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let u of users"><td><b>{{u.firstName}} {{u.lastName}}</b><small>#{{u.id}}</small></td><td>{{u.email}}</td><td>{{u.phone||'—'}}</td><td><span [class.inactive]="u.status!=='ACTIVE'">{{u.status}}</span></td><td>{{u.createdAt|date:'mediumDate'}}</td><td><button class="edit" (click)="open(u)">Edit</button><button class="delete" (click)="remove(u)">Deactivate</button></td></tr></tbody></table></div></div>`,styles:[`
header{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}h1{margin:0;color:#172033}p{color:#7a8492;margin:5px 0}button{border:0;border-radius:8px;padding:10px 16px;background:#185c4a;color:#fff;font-weight:800;cursor:pointer}.card,.table{background:#fff;border:1px solid #e3e8ec;border-radius:14px;margin-bottom:20px}.card{padding:22px}.card h2{margin-top:0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}label{font-size:.8rem;font-weight:700}input,select{display:block;width:100%;padding:10px;margin-top:6px;border:1px solid #dbe1e6;border-radius:8px;background:#fff}.actions{display:flex;gap:8px;margin-top:18px}.secondary{background:#edf0f2;color:#485464}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:13px 15px;border-bottom:1px solid #edf0f2;font-size:.84rem}th{background:#f7f9fa;color:#667181}td small{display:block;color:#929aa5}td span{font-size:.7rem;font-weight:800;color:#18724b;background:#e7f3ed;padding:5px 8px;border-radius:99px}.inactive{color:#a83b2e!important;background:#fde6e3!important}.edit,.delete{padding:7px 10px}.edit{background:#e8f0ff;color:#2456a4;margin-right:5px}.delete{background:#fff0ed;color:#a83b2e}@media(max-width:850px){.grid{grid-template-columns:1fr}}
`]})
export class AdminCustomersComponent implements OnInit{users:User[]=[];showForm=false;editing?:User;form:any={};constructor(private auth:AuthService,private toast:ToastService){}ngOnInit():void{this.load()}load():void{this.auth.getUsers().subscribe({next:r=>this.users=r.data||[],error:()=>this.toast.error('Could not load customers.')})}open(u?:User):void{this.editing=u;this.form=u?{...u,password:''}:{status:'ACTIVE'};this.showForm=true}cancel():void{this.showForm=false;this.editing=undefined;this.form={}}save():void{const op=this.editing?this.auth.updateUser(this.editing.id,this.form):this.auth.createUser(this.form);op.subscribe({next:()=>{this.toast.success(`Customer ${this.editing?'updated':'created'}.`);this.cancel();this.load()},error:e=>this.toast.error(e.error?.message||'Could not save customer.')})}remove(u:User):void{if(!confirm(`Deactivate ${u.email}?`))return;this.auth.deleteUser(u.id).subscribe({next:()=>{this.toast.success('Customer deactivated.');this.load()},error:e=>this.toast.error(e.error?.message||'Could not deactivate customer.')})}}
